MPLUS_TEMPLATE <- "
TITLE: Automated mlVAR input file
DATA:	FILE = @@DATAFILE@@;
VARIABLE:	NAMES = @@VARIABLENAMES@@;
USEVARIABLES = @@USEVARIABLES@@;
MISSING = .;
CLUSTER = @@CLUSTER@@;
LAGGED = @@LAGGED@@; 
ANALYSIS:	TYPE = TWOLEVEL RANDOM;
ESTIMATOR = BAYES;  
PROCESSORS = @@CORES@@;
BITERATIONS = @@ITERATIONS@@;
CHAINS = @@CHAINS@@;
MODEL:	

%WITHIN%
@@WITHINMODEL@@

%BETWEEN%
@@BETWEENMODEL@@

OUTPUT:	TECH1 TECH4 (CLUSTER) TECH8;
SAVEDATA: BPARAMETERS IS @@BAYESSAMPLES@@;
"
